apiVersion: faas.redhat.com/v1alpha1
kind: JSFunction
metadata:
  name: testfunc
spec:
  events: true
  package: |
    {
      "name": "faas-hello-world",
      "version": "0.0.1",
      "description": "A sample FaaS function",
      "author": "lball@redhat.com",
      "license": "MIT",
      "dependencies": {
        "is-number": "^7.0.0"
      }
    }
  func: | 
    const isNumber = require('is-number')

    module.exports = context => {
      const ret = 'This is the test function for Node.js FaaS. Success.';
      if (isNumber(ret)) throw new Error('Something is wrong with modules');
      if (context.cloudevent !== undefined) {
        console.log(`Got cloud event message: "${context.cloudevent.data.message}"`);
      }
      return ret;
    };
    